#!/bin/bash
set -e

echo "Typescript: type checking ..."
npx tsc

echo -e "\nVite: Build bundled web pages ..."
npx vite build

echo -e "\nVite: Building library and node test files ..."
npx vite build --config vite.config-lib.ts

